### ISSUE TITLE
apply basic styling to nyhetsRum.html

### ISSUE THREAD

**Issue by hannesqvarnstrom** [chas-academy/u02-redesign-team-american-clean#18]
use the global grid w/ its readme and apply a basic styling to the page.

**Comment by katepettersson** [comment]
Hi Andrei! I have started a design on this page. Do you want to work together? 

/* Color palette https://coolors.co/1446a0-db3069-f5d547-ebebd3-3c3c3b */ 
@import url("grid.css");

html {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-size: 100%;
}

body {
    background: #EBEBD3;
}

.card {
    background: #80A7EF;
    padding: 15px;
}

.sidebar, .share {
    padding: 15px;
    color: #fff;
}

.sidebar {
    background: #80A7EF;
}

.share {
    background: blue;
}

.post-list {
    list-style-type: none;
    padding: 0;
}

.post-list li {
    padding: 15px;
    background: #80A7EF;
    color: #fff;
    margin-bottom: 15px;
}

**Comment by AndreiAkimochkin** [comment]
Hi, In this way I will star with omOss page. If u want some help. just ask )>
